-- 1. 리더보드 테이블 생성
CREATE TABLE IF NOT EXISTS public.leaderboard (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
user_name VARCHAR(20) NOT NULL,
song_id VARCHAR(50) NOT NULL,
score INT NOT NULL CHECK (score >= 0),
max_combo INT NOT NULL DEFAULT 0,
created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. 곡별 고득점 조회를 위한 인덱스 생성
CREATE INDEX IF NOT EXISTS idx_leaderboard_song_score
ON public.leaderboard (song_id, score DESC);

-- 3. 곡별 Top 10 순위 조회를 위한 View 생성
CREATE OR REPLACE VIEW public.top10_leaderboard AS
SELECT
song_id,
user_name,
score,
max_combo,
created_at,
RANK() OVER (PARTITION BY song_id ORDER BY score DESC) as rank
FROM public.leaderboard;

-- 4. RLS (Row Level Security) 보안 정책 설정
ALTER TABLE public.leaderboard ENABLE ROW LEVEL SECURITY;

-- 읽기 및 입력 권한 설정
CREATE POLICY "Allow public read access"
ON public.leaderboard FOR SELECT
USING (true);

CREATE POLICY "Allow public insert access"
ON public.leaderboard FOR INSERT
WITH CHECK (true);
