-- ══════════════════════════════════════════════════════════════
-- BEATDROP 리더보드 스키마
-- 랭킹은 (곡 × 키모드 × 난이도) 단위로 분리된다.
-- 기존 DB가 있다면 이 파일 전체를 Supabase SQL Editor에 붙여넣고 실행하면
-- 신규 생성 / 마이그레이션 모두 처리된다. (기존 점수 데이터는 보존됨)
-- ══════════════════════════════════════════════════════════════

-- 1. 리더보드 테이블 (신규 생성용)
CREATE TABLE IF NOT EXISTS public.leaderboard (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name   VARCHAR(20) NOT NULL,
    song_id     VARCHAR(50) NOT NULL,
    key_mode    SMALLINT    NOT NULL DEFAULT 4,
    difficulty  VARCHAR(10) NOT NULL DEFAULT 'NORMAL',
    score       INT         NOT NULL CHECK (score >= 0),
    max_combo   INT         NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ DEFAULT NOW()
);

-- 2. 기존 테이블 마이그레이션 (컬럼이 이미 있으면 조용히 넘어감)
ALTER TABLE public.leaderboard
    ADD COLUMN IF NOT EXISTS key_mode SMALLINT NOT NULL DEFAULT 4;

ALTER TABLE public.leaderboard
    ADD COLUMN IF NOT EXISTS difficulty VARCHAR(10) NOT NULL DEFAULT 'NORMAL';

-- 3. 값 검증 제약 (중복 실행 대비해 먼저 DROP)
ALTER TABLE public.leaderboard DROP CONSTRAINT IF EXISTS leaderboard_key_mode_check;
ALTER TABLE public.leaderboard
    ADD CONSTRAINT leaderboard_key_mode_check CHECK (key_mode IN (4, 6));

ALTER TABLE public.leaderboard DROP CONSTRAINT IF EXISTS leaderboard_difficulty_check;
ALTER TABLE public.leaderboard
    ADD CONSTRAINT leaderboard_difficulty_check
    CHECK (difficulty IN ('EASY', 'NORMAL', 'HARD', 'EXPERT'));

-- 4. 랭킹 조회용 인덱스 (구버전 인덱스는 정리)
DROP INDEX IF EXISTS public.idx_leaderboard_song_score;
DROP INDEX IF EXISTS public.idx_leaderboard_song_mode_score;

CREATE INDEX IF NOT EXISTS idx_leaderboard_rank
    ON public.leaderboard (song_id, key_mode, difficulty, score DESC);

-- 5. Top 10 View — 곡 + 키모드 + 난이도별로 순위를 매긴다
DROP VIEW IF EXISTS public.top10_leaderboard;
CREATE VIEW public.top10_leaderboard AS
SELECT
    song_id,
    key_mode,
    difficulty,
    user_name,
    score,
    max_combo,
    created_at,
    RANK() OVER (
        PARTITION BY song_id, key_mode, difficulty
        ORDER BY score DESC
    ) AS rank
FROM public.leaderboard;

-- 6. RLS (Row Level Security) 보안 정책
ALTER TABLE public.leaderboard ENABLE ROW LEVEL SECURITY;

-- 읽기는 공개 (리더보드 조회)
DROP POLICY IF EXISTS "Allow public read access" ON public.leaderboard;
CREATE POLICY "Allow public read access"
    ON public.leaderboard FOR SELECT
    USING (true);

-- ⚠️ 쓰기 권한 회수
--
-- 기존에는 누구나 INSERT 할 수 있어서, 브라우저 콘솔에서 임의 점수를 넣을 수
-- 있었다. 이제 점수 등록은 submit-score Edge Function만 담당한다.
-- (Edge Function은 service role로 동작하므로 RLS를 우회한다.)
--
-- 반드시 Edge Function을 먼저 배포한 뒤 이 구문을 실행할 것.
-- 순서가 바뀌면 그 사이의 점수는 저장되지 않는다.
--     supabase functions deploy submit-score --no-verify-jwt
DROP POLICY IF EXISTS "Allow public insert access" ON public.leaderboard;
